export const citiesByCountry: Record<string, string[]> = {
  CI: ['Abidjan', 'Adjamé', 'Abobo', 'Yopougon', 'Cocody', 'Plateau', 'Marcory', 'Koumassi', 'Port-Bouët', 'Treichville', 'Attécoubé', 'Bingerville', 'Bouaké', 'Yamoussoukro', 'Daloa', 'San-Pédro', 'Korhogo', 'Man', 'Divo', 'Gagnoa', 'Abengourou', 'Agboville', 'Bondoukou', 'Duekoué', 'Guiglo', 'Odienné', 'Séguéla', 'Touba', 'Soubré', 'Tabou', 'Grand-Bassam', 'Assinie', 'Anyama', 'Songon'],
  SN: ['Dakar', 'Thiès', 'Saint-Louis', 'Ziguinchor', 'Kaolack', 'Mbour', 'Rufisque', 'Touba', 'Tambacounda', 'Kolda', 'Diourbel', 'Fatick', 'Louga', 'Matam', 'Kédougou', 'Sédhiou'],
  ML: ['Bamako', 'Sikasso', 'Mopti', 'Ségou', 'Kayes', 'Gao', 'Tombouctou', 'Koutiala', 'Kita', 'Niono', 'Bougouni', 'San', 'Markala'],
  BF: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya', 'Tenkodogo', 'Kaya', 'Dédougou', 'Fada N\'Gourma', 'Manga', 'Ziniaré', 'Léo'],
  GN: ['Conakry', 'Nzérékoré', 'Kindia', 'Kankan', 'Labé', 'Guéckédou', 'Mamou', 'Boké', 'Faranah', 'Kissidougou'],
  TG: ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Dapaong', 'Kpalimé', 'Tsévié', 'Aného', 'Mango'],
  BJ: ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey-Calavi', 'Djougou', 'Bohicon', 'Kandi', 'Abomey', 'Natitingou', 'Ouidah'],
  GH: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast', 'Ho', 'Sunyani', 'Koforidua', 'Wa', 'Bolgatanga'],
  NG: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna', 'Enugu', 'Onitsha', 'Aba', 'Warri', 'Abeokuta', 'Owerri', 'Maiduguri', 'Zaria', 'Ilorin'],
  CM: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda', 'Bafoussam', 'Maroua', 'Ngaoundéré', 'Bertoua', 'Buea', 'Kumba', 'Edéa', 'Limbé', 'Kribi'],
  CG: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Impfondo', 'Owando', 'Ouesso', 'Madingou'],
  CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Goma', 'Bukavu', 'Tshikapa', 'Kolwezi', 'Uvira', 'Likasi', 'Bunia'],
  MA: ['Casablanca', 'Rabat', 'Fès', 'Marrakech', 'Agadir', 'Tanger', 'Meknès', 'Oujda', 'Kénitra', 'Tétouan', 'Safi', 'El Jadida', 'Nador', 'Beni Mellal'],
  DZ: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif', 'Sidi Bel Abbès', 'Biskra', 'Tébessa', 'Tlemcen', 'Béjaïa', 'Skikda', 'Tizi Ouzou'],
  TN: ['Tunis', 'Sfax', 'Sousse', 'Gabès', 'Bizerte', 'Ariana', 'Gafsa', 'Kasserine', 'Monastir', 'Nabeul', 'Kairouan', 'Médenine'],
  EG: ['Le Caire', 'Alexandrie', 'Gizeh', 'Shubra El Kheima', 'Port-Saïd', 'Suez', 'Louxor', 'Assouan', 'El-Mahalla', 'Tanta', 'Asyut', 'Ismaïlia'],
  GA: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga'],
  FR: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Saint-Étienne', 'Grenoble', 'Toulon', 'Aix-en-Provence', 'Brest', 'Nîmes', 'Limoges', 'Clermont-Ferrand', 'Dijon', 'Amiens', 'Angers', 'Villeurbanne', 'Metz', 'Nancy', 'Orléans'],
  BE: ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Louvain', 'Mons', 'Aalst'],
  CA: ['Montréal', 'Toronto', 'Vancouver', 'Ottawa', 'Calgary', 'Edmonton', 'Québec', 'Winnipeg', 'Hamilton', 'Halifax', 'Laval', 'London', 'Brampton', 'Mississauga'],
  US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Atlanta', 'Washington D.C.', 'Miami', 'Seattle', 'Boston', 'San Francisco', 'Orlando', 'Minneapolis'],
  GB: ['Londres', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh', 'Sheffield', 'Bristol', 'Leicester', 'Cardiff', 'Coventry', 'Belfast'],
  DE: ['Berlin', 'Hambourg', 'Munich', 'Cologne', 'Francfort', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund', 'Brême', 'Dresde', 'Hanovre', 'Nuremberg'],
  ES: ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Bilbao', 'Saragosse', 'Malaga', 'Murcie', 'Las Palmas', 'Grenade', 'Alicante', 'Cordoue'],
  IT: ['Rome', 'Milan', 'Naples', 'Turin', 'Palerme', 'Gênes', 'Bologne', 'Florence', 'Venise', 'Catane', 'Vérone', 'Messine'],
  PT: ['Lisbonne', 'Porto', 'Braga', 'Coimbra', 'Funchal', 'Aveiro', 'Amadora', 'Setúbal', 'Almada'],
  CH: ['Zurich', 'Genève', 'Bâle', 'Berne', 'Lausanne', 'Winterthour', 'Lucerne', 'Saint-Gall', 'Lugano'],
  RW: ['Kigali', 'Butare', 'Gisenyi', 'Ruhengeri', 'Byumba', 'Cyangugu'],
  KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi'],
  ET: ['Addis-Abeba', 'Dire Dawa', 'Mekele', 'Gondar', 'Hawassa', 'Bahir Dar', 'Jimma'],
  ZA: ['Johannesburg', 'Le Cap', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Pietermaritzburg'],
  AO: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito', 'Malanje', 'Lubango'],
  MZ: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Quelimane', 'Tete'],
  JP: ['Tokyo', 'Osaka', 'Nagoya', 'Yokohama', 'Kyoto', 'Kobe', 'Sapporo', 'Fukuoka', 'Hiroshima'],
  CN: ['Pékin', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Tianjin', 'Xi\'an'],
  IN: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat'],
  AE: ['Dubaï', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah'],
  SA: ['Riyad', 'Djeddah', 'La Mecque', 'Médine', 'Dammam', 'Khobar', 'Tabuk'],
  LB: ['Beyrouth', 'Tripoli', 'Saïda', 'Tyr', 'Jounieh', 'Zahlé'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Recife', 'Porto Alegre', 'Belém'],
  MX: ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Cancún', 'Mérida', 'León'],
};

export function getCitiesForCountry(countryCode: string): string[] {
  return citiesByCountry[countryCode] || [];
}
